### ISSUE TITLE
I am receiving no tracking data....also a question about pupil size?

### ISSUE THREAD

**Issue by sjssjssjs** [mida-project/eye-tracker-naive#1]
Hello,
Well done on the code. I have installed it and am running the binary with a Tobii EyeTracker 4C. 

I am running:
tobiisteam.exe

I get the following:
TobiiStream v2.0.3

SUCCESS: The connection to the GazeTrack Processing library has been correctly set up!
TobiiState Present

However I get no data stream as per your text files and your example? Also, in the text stream (when I fix it), does one of the parameters correspond to pupil diameter of left and right?

What am I doing wrong? I read that for this to work I do NOT need a licence from Tobii.
Please help,
Simon

**Comment by sjssjssjs** [comment]
Note: I have not got any research licence yet, and am not sure if this is why. Also the more important issue for me is getting direct access to the pupil diameter of each eye. Can you please advise if your source can do this?

**Comment by FMCalisto** [comment]
Dear @simonjosephsmith thank you for your interest in this repository. Soon, we will try to help you by providing an answer to your problem.

**Comment by sjssjssjs** [comment]
Great, thanks.

**Comment by FMCalisto** [comment]
Did you install the [Tobii Eye Tracking Core Software](https://gaming.tobii.com/getstarted/)?

You need to install the software and configure it. Then you need to run it. From here, you can use this repository to extract the users' gaze. Hope that help.

**Comment by sjssjssjs** [comment]
Perfect, that made me get data streaming. However, how can
![data](https://user-images.githubusercontent.com/7038426/108644103-b6f72780-7501-11eb-860b-233cfbcfe9ac.png)
 I access data for the left and right eye pupil diameter?

**Comment by FMCalisto** [comment]
Dear @simonjosephsmith, I am really sorry for the delay in answer your last question. I suggest you to read the documentation of Prof. @AugustoEst concerning this solution. As follows, I will provide a link to the documentation that might help you.

Please try to find a solution to your problem here:

http://web.tecnico.ulisboa.pt/augusto.esteves/GazeTrack/reference/gazetrack/package-summary.html

Hope that help!

**Comment by AugustoEst** [comment]
The TobiiStream used in the GazeTrack library does not provide pupil size information.

**Comment by FMCalisto** [comment]
Thank you Prof. @AugustoEst for your answer. Good luck @simonjosephsmith with your work.

Can I close the issue?

**Comment by sjssjssjs** [comment]
Thank you kindly all. I assume this is only available with a Pro licence
and accessing the 'advanced' API calls?

May I ask if there is any other direct way of accessing the 4C data?

Simon

**Comment by FMCalisto** [comment]
It seems that with [Tobii Pro](https://www.tobiipro.com/) you can access the [pupil size](https://www.tobiipro.com/learn-and-support/learn/eye-tracking-essentials/is-pupil-size-calculations-possible-with-tobii-eye-trackers/). However, you might need to buy a [Pro License](https://developer.tobii.com/license-agreement/).

**Comment by sjssjssjs** [comment]
Hello,

They don't seem to be getting back to me. I know that the API in the
advanced area deals with that. Is there any way to access the data?

S

**Comment by FMCalisto** [comment]
You can also try to explore our [`eye-tracker-setup`](https://github.com/mida-project/eye-tracker-setup) repository which is based on the [`tobii_pro_wrapper`](https://github.com/oguayasa/tobii_pro_wrapper) repository. In the documentation of the [`tobii_pro_wrapper`](https://github.com/oguayasa/tobii_pro_wrapper) repository, you have a [`getPupilSize()`](https://github.com/oguayasa/tobii_pro_wrapper#getpupilsize) method that return the **pupil size**. Hope that help.

**Comment by sjssjssjs** [comment]
Thanks
The biggest issue is Tobii's lack of customer service. They do not seem to
respond to people wanting a research licence.

**Comment by FMCalisto** [comment]
Yes, I agree with you. We tried to surpass several issues while working with such devices. Hope this information helped you on your goals. I will now close the issue.
