### ISSUE TITLE
The meaing of the TobiiStream data

### ISSUE THREAD

**Issue by xiet4** [mida-project/eye-tracker-naive#2]
TobiiStream 1712414.5082 2048.05811935522 306.890588332735 
Could you please explain what's the meaning of the above data? Thank you.

**Comment by FMCalisto** [comment]
Does [this](https://github.com/sajidbaloch/Tobii-Eye-Tracker-4C/issues/1#issuecomment-1092978123) answer your question?

**Comment by xiet4** [comment]
> Does [this](https://github.com/sajidbaloch/Tobii-Eye-Tracker-4C/issues/1#issuecomment-1092978123) answer your question?

Yes, it does, thank you for your reply!

**Comment by FMCalisto** [comment]
I will close now the issue, as the problem is now solved. Any question, please do not hesitate to open a [new issue](new) or comment here.
