### ISSUE TITLE
blinking

### ISSUE THREAD

**Issue by darkzbaron** [mida-project/eye-tracker-naive#4]
Any chance to get the eye blinking data?

**Comment by FMCalisto** [comment]
You could measure the time between no gaze and new gaze found again after that. However, this is not an accurate solution for that. In fact, the eye tracker has many hazards, where the gaze sometimes disappear. Even when the user is not blinking. Therefore, it will be hard to measure that.

**Comment by darkzbaron** [comment]
Thanks so much!

Actually I want this because the screetime tool they ship with the driver does not work anymore, it used to have distance and blinking rate which I am trying to recover with your software. 

Anyway, it looks like they really don't care about their users, thanks for sort of fixing that with your tool!

**Comment by FMCalisto** [comment]
Thank you for your kind words!
